/* import React from "react";

import logo from "./logo.svg";
import "./App.css";
import Navbar from "./Components/Navbar/Navbar";
import Routes from "./Components/Routes/Routes";

function App() {
  return (
    <div className="App">
      <Navbar />
      <Routes />
    </div>
  );
}

export default App;

.App {
    text-align: center;
    /* background-color: #2D2F36; */
/* background-color: #030303;
  }
  
  .App-logo {
    animation: App-logo-spin infinite 20s linear;
    height: 40vmin;
    pointer-events: none;
  }
  .heroLogo {
    height: 60vmin;
    pointer-events: none;
    -webkit-animation: fade-in 4s cubic-bezier(0.39, 0.575, 0.565, 1) 2s both;
    animation: fade-in 4s cubic-bezier(0.39, 0.575, 0.565, 1) 2s both;
  }
  
  .App-header {
    background-color: #2d2f36;
    background-color: #030303;
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    font-size: calc(10px + 2vmin);
    color: white;
  }
  
  .App-link {
    color: #61dafb;
  }
  
  .landingTitle {
    color: #7fbf7f;
    font-family: "Alegreya", serif;
  }
  
  .landingPara {
    max-width: 60%;
    color: #7fbf7f;
    font-family: "Alegreya", serif;
    padding-bottom: 150px;
  }
  
  .landingParaLink {
    max-width: 60%;
    color: #7fbf7f;
    font-family: "Alegreya", serif;
    padding-bottom: 150px;
    text-decoration: underline;
  }
  
  .oneThirdCol {
    width: 30%;
    margin-left: 2.5%;
    float: left;
  }
  
  .projectSubHead {
    width: 100%;
    color: #7fbf7f;
    font-family: "Alegreya", serif;
  }
  
  .projectLogoTitle {
    color: #7fbf7f;
    font-family: "Alegreya", serif;
  }
  /* .projectLogoContainer {
    width: 100%;
  } */
  
 /* .projectLogoCassandra {
    width: 100%;
    -webkit-animation: fade-in-bottom 1.5s cubic-bezier(0.39, 0.575, 0.565, 1)
      4.2s both;
    animation: fade-in-bottom 1.5s cubic-bezier(0.39, 0.575, 0.565, 1) 4.2s both;
  }
  
  .projectLogoCassie {
    width: 100%;
    -webkit-animation: fade-in-bottom 1.5s cubic-bezier(0.39, 0.575, 0.565, 1)
      4.4s both;
    animation: fade-in-bottom 1.5s cubic-bezier(0.39, 0.575, 0.565, 1) 4.4s both;
  }
  
  .projectLogoPlutus {
    width: 100%;
    -webkit-animation: fade-in-bottom 1.5s cubic-bezier(0.39, 0.575, 0.565, 1)
      4.6s both;
    animation: fade-in-bottom 1.5s cubic-bezier(0.39, 0.575, 0.565, 1) 4.6s both;
  }
  
  .projectInfo {
    color: #7fbf7f;
    font-family: "Alegreya", serif;
    padding-top: 550px;
    padding-left: 20%;
    padding-right: 20%;
    text-align: justify;
  }
  
  @keyframes App-logo-spin {
    from {
      transform: rotate(0deg);
    }
    to {
      transform: rotate(360deg);
    }
  }
  
  /* ----------------------------------------------
   * Generated by Animista on 2019-7-3 14:16:50
   * w: http://animista.net, t: @cssanimista
   * ---------------------------------------------- */
  
  /**
   * ----------------------------------------
   * animation fade-in
   * ----------------------------------------
   */
   /*@-webkit-keyframes fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
  @keyframes fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
  
  /* ----------------------------------------------
   * Generated by Animista on 2019-7-3 15:27:51
   * w: http://animista.net, t: @cssanimista
   * ---------------------------------------------- */
  
  /**
   * ----------------------------------------
   * animation fade-in-bottom
   * ----------------------------------------
   */
  /* @-webkit-keyframes fade-in-bottom {
    0% {
      -webkit-transform: translateY(50px);
      transform: translateY(50px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  }
  @keyframes fade-in-bottom {
    0% {
      -webkit-transform: translateY(50px);
      transform: translateY(50px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  } */
